apiVersion: v2
name: doks-lb-scale
description: A Kubernetes controller for scaling DigitalOcean load balancers based on metrics
type: application
version: 0.3.0
appVersion: "v0.3.0-beta"
keywords:
  - kubernetes
  - digitalocean
  - load-balancer
  - autoscaling
  - controller
home: https://github.com/digitalocean-labs/doks-lb-scale
sources:
  - https://github.com/digitalocean-labs/doks-lb-scale
maintainers:
  - name: jkpe
    email: jpearce@digitalocean.com
kubeVersion: ">=1.31.0"
