{{- if .Values.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "doks-lb-scale.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "doks-lb-scale.labels" . | nindent 4 }}
type: {{ .Values.secret.type }}
data:
  token: {{ .Values.config.doApiToken | b64enc }}
{{- end }}
